#!/bin/bash

# Use the space created by the server to record asciinema content
RECORDS_DIR=$SNAP_DATA/records

echo -n "Enter title of your recording: "
read title

datefmt=`date +"%T.%d-%m-%y"`
filename=${title// /_}_$datefmt
filename=${title// /_}_$datefmt.asciinema

asciinema rec "$RECORDS_DIR/$filename" -t "$title" -c byobu


# READ IP filename
ip=`cat "$SNAP_DATA/server_ip"`
echo "Your recording is available at:"
qrencode -t ASCII "http://$ip/$filename"
